### ISSUE TITLE
Feature Request: Cut custom fonts

### ISSUE THREAD

**Issue by minthemiddle** [leoncvlt/loconotion#104]
To make the output even leaner and privacy-oriented, it would be great if you could programmatically remove the custom fonts and replace it with the OS default one (`-apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;`).

**Comment by sueszli** [comment]
I think some users would prefer having the original fonts used by Notion. But you can already set the font that you want in the TOML file.

**Comment by sueszli** [comment]
I genuinely agree with you though on the part that getting rid of the config TOML file would significantly improve the projects maintainability.
