### ISSUE TITLE
`--dark-theme` argument has no effect

### ISSUE THREAD

**Issue by sueszli** [leoncvlt/loconotion#116]
The `--dark-theme` argument has no effect.

Dark themed pages can only be parsed when using the `.toml` file to scrape.

**Comment by sueszli** [comment]
I fixed this issue in my fork: https://github.com/sueszli/notionSnapshot

**Comment by kmlbgn** [comment]
Is it possible to keep the toggle option somehow ?

**Comment by sueszli** [comment]
@kmlbgn i don't know what you mean

**Comment by kmlbgn** [comment]
@sueszli I meant having a button to shift from dark to light in the scrapped page.
