### ISSUE TITLE
Discord server for devs

### ISSUE THREAD

**Issue by sueszli** [leoncvlt/loconotion#118]
I think loconotion is a real competition for super, potion and other SaaSs and would love to contribute more regularly.

Could we maybe set up a discord server for devs?
This would make discussions a lot easier.

Also: why don't we just download the files as html in notion itself and just use custom CSS that give it the original look?

**Comment by 2m** [comment]
> why don't we just download the files as html in notion itself and just use custom CSS that give it the original look?

When I was looking at the Notion exported HTML, it was quite primitive. More advanced features, like tables where exported as a very simplified static tables.

Discord channel sounds good!

**Comment by sueszli** [comment]
Awesome!

Could we maybe still do this styling thing as a small side project on this repository?

My issue right now is that I have many notion pages with super large files in them and using notion would help me download them all reliably.
