### ISSUE TITLE
make "Name column on tables become a link" optional

### ISSUE THREAD

**Issue by dosoft** [leoncvlt/loconotion#12]
It's a great feature, but sometimes we just need tables as a way to format information and don't need a conversion of the name column to the link.

Note, that if the table includes multiple (let's say 50 rows) then this conversion takes a LOT of time.

**Comment by leoncvlt** [comment]
Implemented via the `no-links` config option as of 4c4c5069a4c88c4620be17fb106bcc920ac6be27 😃
