### ISSUE TITLE
Exported Table Row out of proportion

### ISSUE THREAD

**Issue by sampolgar** [leoncvlt/loconotion#120]
<img width="822" alt="Screen Shot 2022-08-16 at 9 52 55 pm" src="https://user-images.githubusercontent.com/39210767/184873221-e3d8c737-6239-41e9-94ca-2717623b8cc5.png">

Hola, not sure why all my exported tables have huge row sizes, is there something wrong in my export config?

**Comment by sueszli** [comment]
I also had the same issue.
Tables without a title or a hidden title get shifted up.
