### ISSUE TITLE
[feature request] GitHub Action that will deploy to github pages.

### ISSUE THREAD

**Issue by aahnik** [leoncvlt/loconotion#21]
GitHub Pages can be used to host static content easily.

It would be great if there was a  GitHub action, that could do the job. It would rebuild the pages periodically or when triggered by user. The github repo would contain the html files to serve.

So the user experience would be something like this:
1. Make your desired notion pages public
2. Create a github repo from template ( the template would contain the gh aciton workflow script and empty config file ) to host the static content
3. edit the config file to set the pages and other things
4. the script will be triggered on a push to main branch
5. the script can be run manually at times, or will run periodically ( cron expression set by user) 

GitHub urls are `user.github.com/repo/page_slug`

Users could also use custom domain (configure gh page url in repo settings)
thus: `custom.com/page_slug`

**Comment by aahnik** [comment]
@leoncvlt the idea of static page is great. it will not update live. I dont want my changes to go live when I am editing. Notion suggests to use a seperate staging area, but thats bad.

When this thing is deployed in GitHub pages, the rebuild can be triggered by many things. GitHub provides a ton of ways.

**Comment by artxia** [comment]
Look here

https://github.com/artxia/Action-NotionSite

**Comment by aahnik** [comment]
thanks a lot! @artxia

**Comment by aahnik** [comment]
the instructions in readme is extremely well written. I really appreciate that.

thanks a lot for the effort. I hope this will help many.

**Comment by leoncvlt** [comment]
Nice work! Mind if I put a link to that in the readme @artxia ?

**Comment by artxia** [comment]
> Nice work! Mind if I put a link to that in the readme @artxia ?

Sure, it would be my pleasure.
