### ISSUE TITLE
[bug] Cached font files are not used

### ISSUE THREAD

**Issue by drunkhacker** [leoncvlt/loconotion#26]
I can definitely see it downloads font files and caches them using hashed filenames, but it doesn't persist changed stylesheet file. 

It iterates css rules, finds font-face rule and downloads the web font file, and changes the style object.
https://github.com/leoncvlt/loconotion/blob/a3d22a24e84cda251e2d8bc56d26cbe8a65a53ff/loconotion/notionparser.py#L426-L435

But it doesn't persist changed stylesheet object, as it results in requesting non-existing files as it refers to the original filename like `/lyon-text-semibold-acb7f110189034ff6a1afa4b730be0ed.woff` rather than `25bf88e58579843c4aef766a6afe75998af40282.woff` 

Please take a look at this, and I hope to see this is fixed soon!

Thank you for making this great program.

**Comment by leoncvlt** [comment]
Should be fixed as of 71fbbb2cecc07f92624e30797c0cb49efb1fb12d, thanks for the pull request!
