### ISSUE TITLE
Parser crashes with unexpected behavior of scrollIntoView() on table block

### ISSUE THREAD

**Issue by adrenalin8231** [leoncvlt/loconotion#3]
Greetings from Korea, the first non-English language environment [where Notion officially supports](https://www.notion.so/157765353f2c4705bd45474e5ba8b46c#5d4ede69e3824d6bbba22ef95f739174) :D

# Issue

[notionparser.py#L431](https://github.com/leoncvlt/loconotion/blob/73c21cc6079e9a242400c7bfb8ed92bf39247d8e/loconotion/notionparser.py#L431) seems to expect that javascript `scrollIntoView()` will make `table_row_hover_target` visible.
But instead...

![image](https://user-images.githubusercontent.com/30610416/89894926-e1dcf680-dc15-11ea-961d-ce9c69be3bee.png)

`table_row_hover_target` is still invisible, behind the table header.

## Environment
* MacOS 10.15.5 Catalina
* `(Session info: chrome=84.0.4147.105)`
* loconotion is on current master(73c21cc)

# Workaround (if this issue affects everyone)

I managed to resolve this issue - quick and (so) dirty - by injecting some [scroll-margin-top](https://www.bram.us/2020/03/01/prevent-content-from-being-hidden-underneath-a-fixed-header-by-using-scroll-margin-top/) on `div[data-block-id='{table_row_block_id}']` and then ``scrollIntoVIew()`` into it.

```python
                # for each row, hover the mouse over it to make the open button appear,
                # then grab its href and wrap the table row's name into a link
                table_row_block_id = table_row["data-block-id"]
                table_row_scroll_target = self.driver.find_element_by_css_selector(
                    f"div[data-block-id='{table_row_block_id}']"
                )
                table_row_hover_target = self.driver.find_element_by_css_selector(
                    f"div[data-block-id='{table_row_block_id}'] > div > div"
                )
                # need to scroll the row into view or else
                # the open button won't visible to selenium
                self.driver.execute_script(
                    "arguments[0].style.scrollMarginTop = '100px'; arguments[0].scrollIntoView();", table_row_scroll_target
                )
```

I think it would be possible to check `div.notion-table-view-header-cell` and  `div.notion-topbar`'s heights to improve this, but since I don't have any experience on Selenium it will take too much time for me to do it alone.

**Comment by leoncvlt** [comment]
Hello! I can't seem to replicate this bug. Do you have an example page I could use / scrape?

**Comment by leoncvlt** [comment]
Forgot about this - I revised the table parsing method in the commit b1705ed - should have fixed it - feel free to reopen the issue if that isn't the case!
