### ISSUE TITLE
Blog post properties view distorted on iOS Safari

### ISSUE THREAD

**Issue by mabdullahabid** [leoncvlt/loconotion#30]
The properties section under the title and before the blog post content is distorted with weird padding all over the place on Safari on iOS. I'll try and get screenshots.

Has anyone else encountered this issue?

**Comment by leoncvlt** [comment]
Might be related to #1

**Comment by mabdullahabid** [comment]
Yup, it's exactly the same thing. Maybe we can continue the conversation there and you can close this one.
