### ISSUE TITLE
Add support to Google Analytics

### ISSUE THREAD

**Issue by rickyking** [leoncvlt/loconotion#32]
Thanks for creating such a great library.

I tried to hack your TOML file without a success. 

I would like to add the following code (from Google Analytics) to each page's header:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxxxxxxx"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-xxxxxxxxx');
</script>
```

Any possible way? 

This would be great to be able to track how user navigate through the site.

**Comment by leoncvlt** [comment]
You should be able to do this by putting that code on a separate js file and then using the `site.inject` parameter to inject that into the head:

```
  [[site.inject.head.script]]
  type="text/javascript"
  src="your-analytics.js"
```

**Comment by rickyking** [comment]
Smart Idea, let me try and get back to you 👍

**Comment by rickyking** [comment]
Hi @leoncvlt . It's working quite well. 

I share back the code: https://github.com/TradingLogic/wiki

Also I use github actions to automate the deployment.
