### ISSUE TITLE
Rendering bug with inline references

### ISSUE THREAD

**Issue by StruffelProductions** [leoncvlt/loconotion#39]
Using inline references causes HTML an HTML rendering bug due to an oversized svg icon.
**Expected result (as seen on Notion.so):**
![image](https://user-images.githubusercontent.com/31403260/109933921-376d1380-7ccc-11eb-9ae1-8fabb8361db5.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/31403260/109934479-e14ca000-7ccc-11eb-9caf-cfa16c3f301a.png)

**Steps to reproduce:**
Download the following Notion page with default settings: https://www.notion.so/cc0textures/Loconotion-Rendering-bug-demonstration-1f1cda00e3ff4d5b9e70c8232210b7d7

`python loconotion https://www.notion.so/cc0textures/Loconotion-Rendering-bug-demonstration-1f1cda00e3ff4d5b9e70c8232210b7d7`

I am using Locomotion master with this commit being the latest: https://github.com/leoncvlt/loconotion/commit/f580af4a8e6eb77120a119bf920560789edc6f7e

Windows 10 20H2
Chrome 88.0

**Any tips for temporary workarounds would be greatly appreciated (for example a way to just hide the small icon which is causing the issue).**

**Comment by leoncvlt** [comment]
Hey, should be fixed in https://github.com/leoncvlt/loconotion/commit/001c332839fd0336573fb0d465a982c39d4e431d!

**Comment by leoncvlt** [comment]
Going to close this, let me know if this is still an issue @StruffelProductions
