### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ozanozyegen** [leoncvlt/loconotion#40]
Is it possible to add Disqus comments below some pages?

**Comment by leoncvlt** [comment]
I don't have experience using Disqus, but looking at their [installation page](https://help.disqus.com/en/articles/1717112-universal-embed-code), it sounds like you might try embedding a custom .js script  in the body with the toml configuration, and within this script create a `div` with id `disqus_thread`, append it at the bottom of the page, and include the code from that installation page to initialize disqus.
