### ISSUE TITLE
Add command option to change where the website is saved

### ISSUE THREAD

**Issue by ghost** [leoncvlt/loconotion#57]
I think that editing the program to let the user choose where to save the website would be better than just making a dist folder in the working directory. 

the option would probably be 
-d /directory

where d stands for destination.

**Comment by douglasjarquin** [comment]
I've had success overriding the "output" config option as in https://github.com/leoncvlt/loconotion/blob/master/loconotion/notionparser.py#L54.

I have the following line in my .toml:

```
output = "public"
```
