### ISSUE TITLE
Enable Custom Favicons

### ISSUE THREAD

**Issue by I-Dont-Remember** [leoncvlt/loconotion#68]
It's a minor thing, but being able to add a custom favicon would be a nice to have for personalization of these sites. In the future could explore other cosmetic adjustments to pages, but this would be relatively straightforward change, just requires ensuring the metadata is set correctly if the person provides a file path. Probably makes sense to handle in site config file.

https://favicon.io/tutorials/what-is-a-favicon/

https://stackoverflow.com/questions/11893478/add-favicon-to-website

**Comment by leoncvlt** [comment]
This can already be done using a custom element injection on the head, in fact, the example site does it:
```
  [[site.inject.head.link]]
  rel="icon" 
  sizes="16x16"
  type="image/png"
  href="/example/favicon-16x16.png"
```
