### ISSUE TITLE
List bullets not displaying properly

### ISSUE THREAD

**Issue by leshchenko1979** [leoncvlt/loconotion#71]
After I updated my notion/loconotion website yesterday, the list bullets points disappeared.

Anyone has the same problem?

 To be:

![image](https://user-images.githubusercontent.com/60138889/127982401-193b8023-9824-4c91-a5b9-f5b7786f4619.png)

As is:

![image](https://user-images.githubusercontent.com/60138889/127982436-be40c3b1-30ed-4763-9d7c-0a046fb2d1aa.png)

**Comment by leshchenko1979** [comment]
It turned out that the lists on the original Notion site contain instructions like `--pseudoBefore--content: "1."`, and a css file from the original Notion site has the following code:

```

/* ==================================================================== */
/* Customizable class utilities.
 * see shared/cssHelpers.ts
 *
 * Use css variables to customize styles for pesudoselectors we
 * can't easily target from inline style properties.
 *
 * Each class defined below should be added to customizableClassnameHelpers.ts.
 * For each CSS property, use var(`--${className}--${propertyName}`) as the value.
 *
 * We use camelCase names here so they're easier to write in Typescript.
 * TODO: use something like linaria to automate this shenanigans.
/* ==================================================================== */

.pseudoAfter:after {
  color: var(--pseudoAfter--color);
  content: var(--pseudoAfter--content);
  border: var(--pseudoAfter--border);
  width: var(--pseudoAfter--width);
  height: var(--pseudoAfter--height);
  display: var(--pseudoAfter--display);
  background: var(--pseudoAfter--background);
}

.pseudoBefore:before {
  color: var(--pseudoBefore--color);
  content: var(--pseudoBefore--content);
  border: var(--pseudoBefore--border);
  width: var(--pseudoBefore--width);
  height: var(--pseudoBefore--height);
  display: var(--pseudoBefore--display) !important;
  background: var(--pseudoBefore--background);
}

.pseudoSelection ::selection {
  color: var(--pseudoSelection--color);
  background: var(--pseudoSelection--background);
  text-shadow: var(--pseudoSelection--textShadow);
}
```

After I inserted this code into one of my local css files, the bullets and list item numbers started displaying properly.

So, I wonder what a permanent fix for this would look like. It seems like loconotion might be deleting too much of the original notion code? @leoncvlt

**Comment by leoncvlt** [comment]
Curious, it shouldn't be stripping any css. Thanks for the heads up, I'll have some time to look at this this weekend 😃

**Comment by jiatern** [comment]
Facing the same issue here. I am not well versed with html/css but apparently I replaced the html file with an older version that was parsed few weeks ago (without changing the CSS file), the bullets appeared.  

Not sure if it helps but I've attached both here.
[html.zip](https://github.com/leoncvlt/loconotion/files/6950513/html.zip)

**Comment by leshchenko1979** [comment]
> Facing the same issue here. I am not well versed with html/css but apparently I replaced the html file with an older version that was parsed few weeks ago (without changing the CSS file), the bullets appeared.  
> 
> 
> 
> Not sure if it helps but I've attached both here.
> 
> [html.zip](https://github.com/leoncvlt/loconotion/files/6950513/html.zip)
> 
> 

Obviously, the fix you described prevents you from updating your site.

You can insert the code above into your loconotion.css and it should fix the problem after your run the scan once again.

I will be adding a PR about this a bit later today.

**Comment by leshchenko1979** [comment]
@jiatern , here you go
