### ISSUE TITLE
Wide pages seem to remain narrow

### ISSUE THREAD

**Issue by leshchenko1979** [leoncvlt/loconotion#72]
In my Notion workspace, I have a page that is set to be wide: https://www.notion.so/flipio/40-e6c314bb10fa4262936e680100a14719
However, when processed with loconotion and uploaded to my hosting, it remains narrow: https://flipio.ru/invest.html

**Comment by wbsth** [comment]
Have this same problem. You can easily reproduce that by trying to generate example page, using `python loconotion .\example\example_site.toml`

[Original page](https://www.notion.so/Loconotion-Example-Page-03c403f4fdc94cc1b315b9469a8950ef#ffa3779739fd4ba286b7f8462f9e8e60):
![chrome_ExwGSuRFHe](https://user-images.githubusercontent.com/18263943/130095753-172b743f-4241-4b9b-a704-83dfbd45b645.jpg)

After using loconotion:
![chrome_6Tl9xjcXbG](https://user-images.githubusercontent.com/18263943/130095609-8e909548-1a37-4c65-8819-24a07446c966.jpg)

**Comment by leshchenko1979** [comment]
> Have this same problem. You can easily reproduce that by trying to generate example page, using `python loconotion .\example\example_site.toml`
> 
> 
> 
> [Original page](https://www.notion.so/Loconotion-Example-Page-03c403f4fdc94cc1b315b9469a8950ef#ffa3779739fd4ba286b7f8462f9e8e60):
> 
> ![chrome_ExwGSuRFHe](https://user-images.githubusercontent.com/18263943/130095753-172b743f-4241-4b9b-a704-83dfbd45b645.jpg)
> 
> 
> 
> After using loconotion:
> 
> ![chrome_6Tl9xjcXbG](https://user-images.githubusercontent.com/18263943/130095609-8e909548-1a37-4c65-8819-24a07446c966.jpg)
> 
> 

The issue you are pointing out is about something else. I had this one and find a fix too. Will upload the fix a bit later.

**Comment by wbsth** [comment]
> The issue you are pointing out is about something else. I had this one and found a fix too. Will upload the fix a bit later.

Ah, the title of issue misleaded me a bit. Nevertheless, thanks for that fixes.
