### ISSUE TITLE
Bad rendering on ios and android

### ISSUE THREAD

**Issue by PaysanBarbare** [leoncvlt/loconotion#83]
Hello,

Loconotion works well for my notion's website, but it's not display it full width on smartphone :

This is the original : 
https://boiteaoutils.notion.site/boiteaoutils/Boite-A-Outils-BAO-a8530d0ca7834f36b2a8ea856deba06b
![Screenshot_20211025-122017](https://user-images.githubusercontent.com/77626202/138679219-44bff4dd-7897-433c-a13b-a60d4de54c5d.jpg)

And after loconotion :
http://boiteaoutils.xyz/boite-a-outils-bao.html
![Screenshot_20211025-122030](https://user-images.githubusercontent.com/77626202/138679448-68d930b3-2870-4b23-82ff-9cb51cebe73a.jpg)

Thanks for your help !

**Comment by leshchenko1979** [comment]
Please check if the above PR solves your problem.

**Comment by PiktCai** [comment]
It haven't been solved completely. There is still blanks on the both sides of my site though the title is normal now.
My site is https://static.picozai.tk
