### ISSUE TITLE
Links on sub pages don't works

### ISSUE THREAD

**Issue by PaysanBarbare** [leoncvlt/loconotion#86]
Hello,
When I click on a link in subpages of Notion wich refered to other notions pages, it doesn't do anything. Right click then "Open in a new tab" works.
It works when I removed  `contenteditable="true" data-content-editable-leaf="true" ` near each link in the source code of generated html pages.

**Comment by PaysanBarbare** [comment]
Hello,

Yes it still persist.

**Comment by leshchenko1979** [comment]
Can you give some more details? Any screenshots, pieces of code?

Have you tried repairing the page? Notion changes the layout often, and if you reparse the page today, it might work.
