### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by philfreo** [leoncvlt/loconotion#9]
This is a great project, thank you! I'm using it for https://github.com/philfreo/sjc.vote. 

I tried getting this to run inside docker but I had trouble with the chrome driver stuff. It'd be nice to have a more portable way to run this (perhaps even inside GitHub Actions) without having to install all the dependencies. Perhaps that would even allow some sort of integration that auto-builds upon a change in Notion.

**Comment by leoncvlt** [comment]
Actually I've got a pull request #5 that should enable docker support - I don't have much experience in Docker, does that look OK to you?

**Comment by philfreo** [comment]
Oh nice, I should have checked PRs first
