### ISSUE TITLE
Fork with a couple of PRs merged

### ISSUE THREAD

**Issue by 2m** [leoncvlt/loconotion#98]
I am maintaining a fork at https://github.com/2m/loconotion that has some PRs merged:

* #94
* #95
* #96 (rebase of #60 by @leshchenko1979)
* #97
* #99
* #100
* #101
* #102

There is also a Docker image being built automatically from the `main` branch: https://github.com/2m/loconotion/pkgs/container/loconotion. Here is an example GitHub Action that uses this Docker image to run loconotion: https://github.com/2m/nemunasring/blob/60b305b8ea105cadbab72cadeeb1ebc5dac3fce8/.github/workflows/notion-to-gh-pages.yml#L19-L24

**Comment by leoncvlt** [comment]
Hey, thanks for this! I haven't had time to look at my Github issues lately, I'll check out your pull requests later today! Thanks again!

**Comment by leoncvlt** [comment]
Thanks a lot for your contributions, I've merged them into `main`!

**Comment by 2m** [comment]
Thanks! I will create another PR with README.md updates regarding new configuration option.
